### ISSUE TITLE
Slider/Ok mantığı

### ISSUE THREAD

**Issue by vedatduha** [MuhammetDilmac/AndroidExamples#1]
```java
   private void setArrowStatus() {
        if ( cityIndex == 0 ) {
            if ( arrowRightButton.getVisibility() == View.INVISIBLE )
                arrowRightButton.setVisibility(View.VISIBLE);

            if ( arrowLeftButton.getVisibility() == View.VISIBLE )
                arrowLeftButton.setVisibility(View.INVISIBLE);
        }
        else if ( cityIndex == cities.length() - 1 ) {
            if ( arrowLeftButton.getVisibility() == View.INVISIBLE )
                arrowLeftButton.setVisibility(View.VISIBLE);

            if ( arrowRightButton.getVisibility() == View.VISIBLE )
                arrowRightButton.setVisibility(View.INVISIBLE);
        }
        else {
            if ( arrowLeftButton.getVisibility() == View.INVISIBLE )
                arrowLeftButton.setVisibility(View.VISIBLE);

            if ( arrowRightButton.getVisibility() == View.INVISIBLE )
                arrowRightButton.setVisibility(View.VISIBLE);
        }
    }    
```
Bu yapı kısaca nasıl çalışıyor?

**Comment by MuhammetDilmac** [comment]
Şöyle ki Slider oklarında 3 farklı durum var bunlar;
1. İlk Slide'da iken sola gidemez sadece sağa git oku bulunmalı.
2. Son Slide'da iken sağa gidemez sadece sola git oku bulunmalı.
3. Ne ilk ne son slide'de iken iki okta bulunmalı.

Değişkenler;
- **cityIndex** bizim aktif olan slide numaramızı tutmaktadır.
- **arrowRightButton** slider da sağa giden ok işaretidir.
- **arrowLeftButton** slider da sola giden ok işaretidir.

Fonksiyonlar;
- **getVisibility()** objenin görünür olup olmadığını döndürür.
- **setVisibility(PARAM)** objenin görünürlüğünü parametre olarak set eder. Parametreler;
  - **View.VISIBLE** bir objenin görünür olduğu anlamını taşır.
  - **View.INVISIBLE** bir objenin görünmez olduğu anlamını taşır.

```java
if ( cityIndex == 0 ) {
    if ( arrowRightButton.getVisibility() == View.INVISIBLE )
        arrowRightButton.setVisibility(View.VISIBLE);

    if ( arrowLeftButton.getVisibility() == View.VISIBLE )
        arrowLeftButton.setVisibility(View.INVISIBLE);
}
```
Yukarıda ki kodda eğer mevcut slide index'i 0 ise;
- Sağ ok gözünmez ise onu görünür yap
- Sol ok görünür ise onu görünmez yap

```java
else if ( cityIndex == cities.length() - 1 ) {
    if ( arrowLeftButton.getVisibility() == View.INVISIBLE )
        arrowLeftButton.setVisibility(View.VISIBLE);

    if ( arrowRightButton.getVisibility() == View.VISIBLE )
        arrowRightButton.setVisibility(View.INVISIBLE);
}
```
Yukarıda ki kodda eğer mevcut slide index'i sonuncu ise;
- Sol ok görünmez ise görünür yap.
- Sağ ok görünür ise görünmez yap.

```java
else {
    if ( arrowLeftButton.getVisibility() == View.INVISIBLE )
        arrowLeftButton.setVisibility(View.VISIBLE);

    if ( arrowRightButton.getVisibility() == View.INVISIBLE )
        arrowRightButton.setVisibility(View.VISIBLE);
}
```
Yukarıda ki kodda eğer mevcut slide index'i ne sonuncu nede başlangıç ise;
- Sol ok görünmez ise görünür yap.
- Sağ ok görünmez ise görünür yap.


Eğer cevap yeterli ise Issue'yu aşağıda bulunan close butonu ile kapatmanı rica edeceğim :)

**Comment by MuhammetDilmac** [comment]
Geri dönüş alınamadığı için Issue kapatılmıştır.
