### ISSUE TITLE
CleanText

### ISSUE THREAD

**Issue by vedatduha** [MuhammetDilmac/AndroidExamples#7]
```java
 public void onClickClearText(View view) {
        String cleanText = "";
        String input     = inputText.getText().toString();
        Pattern pattern  = Pattern.compile("[A-Za-zİıĞğÜüŞşÖöÇç]"); // Bu Kısımda tanımadığı karakterleri mi tanıttın?-->

        Matcher matcher  = pattern.matcher(input); // Matcher Ne işe yarar?

        int totalInputSize = input.length();

        while( matcher.find() )
            cleanText = cleanText.concat(matcher.group(0));  // Matcher.group(0)?

        int cleanTextSize = cleanText.length();

        Intent resultIntent = new Intent();
        resultIntent.putExtra("cleanText", cleanText);
        resultIntent.putExtra("invalidSize", totalInputSize - cleanTextSize); 
        setResult(Activity.RESULT_OK, resultIntent);
        finish();
```
  Pattern,Matcher nasıl kullanılıyor tam olarak? bir de çalışma mantıkları nasıl tam olarak mantığını anlayamadım açıklayabilirsen sevinirim :))

**Comment by MuhammetDilmac** [comment]
## Genel Açıklama
Aslında burada pattern dediğimiz şey bir Regex'dir. Regex'in ne olduğunu anlaman için şu kaynakları vereyim.
- [Düzenli İfadeler (Regular Expressions) - İTÜ Bilgi İşlem Daire Başkanlığı](https://bidb.itu.edu.tr/seyir-defteri/blog/2013/09/08/d%C3%BCzenli-i-fadeler-(regular-expressions))
 - [Alper Sarı   &raquo; Regular Expression (Kurallı İfadeler) - Alper sarı Sabancı Üniversitesi](http://myweb.sabanciuniv.edu/alper/regular-expression-duzenli-ifadeler/)
- [Regex Denemeleri Yapmak için Regex101](regex101.com)
- [Java'da Regex Denemeleri Yapmak için FreeFormatter](https://www.freeformatter.com/java-regex-tester.html)

Java'da Regex ile geçerli karakter olarak A-Z ve a-z aralığını verdim. Fakat türkçe'de bulunan özel karakterleri buna elle eklemek gerekti ki bunlarda; İ, ı, ğ, Ğ, Ü, ü, Ş, ş, Ö, ö, Ç, ç harfleridir. Bunların dışında ki tüm karakterler ise benim istemediğim karakterler. Bu yüzden istediğim karakterleri yazarak(white listing) sadece bunların bulunmasını istedim(patter.matcher). Java 7'de Türkçe karakter desteği için Pattern.compile'a `Pattern.UNICODE_CHARACTER_CLASS` parametresini  verince Türkçe karakterleri belirtmeye gerek yok. Fakat Anroid'de bu desteklenmiyor.

## Detay
1. İstediğim karakterleri belirtmek için burada bir regex kuralı oluşturdum.
```java
Pattern pattern  = Pattern.compile("[A-Za-zİıĞğÜüŞşÖöÇç]");
```

2. İstediğim karakterlerin hangi girdiden alınacağını belirttim. Bu bağlamda matcher'a eşleşen veriler döndürülüyor.
```java
Matcher matcher  = pattern.matcher(input);
```

3. İstediğim karakterleri tek tek bulmak için girdi üzerinde arama yaptırıyorum. Her bulduğu veride cursor'u ileri kaydırıyor bu metod.
```java
matcher.find()
```

4. Bulunan veriyi bana döndürmesi için bu metodu kullanıyorum.
```java
matcher.group(0)
```

Detaylar için;
- [Java - Matcher](https://docs.oracle.com/javase/7/docs/api/java/util/regex/Matcher.html)

**Comment by MuhammetDilmac** [comment]
24 saat içinde bir geri dönüş alamadığım için Issue'yu kapatıyorum. Anlamadığınız yer olursa buraya yorum olarak yazarsınız.
